In [1]:
import pandas as pd

# Example DataFrame
data = pd.read_csv("../zoo-info.csv")
df = pd.DataFrame(data)

# Combine longitude and latitude into a new 'location' column
df['location'] = df.apply(lambda row: [row['longitude'], row['latitude']], axis=1)

# Show the updated DataFrame

    id                           name  category            for  \
0    0                  Entrance/Exit     place            all
1    1             Ah Meng Restaurant      food            all
2    2                      KidzWorld    region          young
3    3                       RepTopia    region          young
4    4               White Rhinoceros     place            all
..  ..                            ...       ...            ...
61  61  Toilet / Water Refill Point 8  facility            all
62  62                   Nursing Room  facility  parents, baby
63  63                   Nursing Room  facility  parents, baby
64  64                 KidzWorld Shop      shop            all
65  65       Singapore Zoo Photo Shop      shop            all

                                          description    operating_hours  \
0             The Entrance and Exit of Singapore Zoo.  8:30am – 6:00pm\n
1   With a casual atmosphere and a variety of food...  8:30am – 6:00pm\n
2   Step into the new KidzWorld — Home of the Rang...  8:30am – 6:00pm\n
3   Home to over 60 species of reptiles and amphib...  8:30am – 6:00pm\n
4   A huge animal that feeds exclusively on grass,...  8:30am – 6:00pm\n
..                                                ...                ...
61             Toilet and place to get drinking water  8:30am – 6:00pm\n
62                                       Nursing room  8:30am – 6:00pm\n
63                                       Nursing room  8:30am – 6:00pm\n
64  Bring home a memento or two from the KidzWorld...    9:30am – 6:00pm
65  Complete your Singapore Zoo journey with a cus...    9:00am – 6:30pm

    cluster   longitude  latitude                location
0         9  103.790457  1.404228  [103.790457, 1.404228]
1         0  103.793580  1.404160    [103.79358, 1.40416]
2         1  103.796225  1.403150   [103.796225, 1.40315]
3         5  103.794698  1.402405  [103.794698, 1.402405]
4        11  103.793461  1.402918  [103.793461, 1.402918]
..      ...         ...       ...                     ...
61        4  103.794438  1.405990   [103.794438, 1.40599]
62        5  103.794671  1.402400    [103.794671, 1.4024]
63        9  103.790287  1.404060   [103.790287, 1.40406]
64        7  103.796539  1.403264  [103.796539, 1.403264]
65        9  103.790459  1.404014  [103.790459, 1.404014]

[66 rows x 10 columns]

In [2]:
df.head()

,id,name,category,for,description,operating_hours,cluster,longitude,latitude,location
0,0,Entrance/Exit,place,all,The Entrance and Exit of Singapore Zoo.,8:30am – 6:00pm\n,9,103.790457,1.404228,"[103.790457, 1.404228]"
1,1,Ah Meng Restaurant,food,all,With a casual atmosphere and a variety of food...,8:30am – 6:00pm\n,0,103.793580,1.404160,"[103.79358, 1.40416]"
2,2,KidzWorld,region,young,Step into the new KidzWorld — Home of the Rang...,8:30am – 6:00pm\n,1,103.796225,1.403150,"[103.796225, 1.40315]"
3,3,RepTopia,region,young,Home to over 60 species of reptiles and amphib...,8:30am – 6:00pm\n,5,103.794698,1.402405,"[103.794698, 1.402405]"
4,4,White Rhinoceros,place,all,"A huge animal that feeds exclusively on grass,...",8:30am – 6:00pm\n,11,103.793461,1.402918,"[103.793461, 1.402918]"

In [ ]:
df.to_csv("../zoo-info.csv", index=False)